"""The browser extension's projected FPts/G, from the same snapshot the sim reads.

    python3 .claude/skills/projections/extension_data.py   # rewrite src/data/player-data.ts

`SKILL.md` owns when to run this.
"""
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import overrides
import sleeper

REPO = os.path.join(HERE, os.pardir, os.pardir, os.pardir)
ROSTERS = os.path.join(REPO, "strategy", "lineup-math", "rosters", "roster-*.json")
POOL = os.path.join(REPO, "strategy", "lineup-math", "data", "players-*.json")
OUT = os.path.join(REPO, "src", "data", "player-data.ts")


def player_rates(roster_players, feed_rows, pool_players=()):
    """League spelling -> FPts/G for every rostered player, then every unrostered
    player in last season's pool, then every remaining feed player under the
    feed's spelling; plus the rostered names with no projection. Same precedence
    as the sim: override, then feed, then `sleeper.unprojected_rate`."""
    idx = sleeper.index(feed_rows)
    rostered = {p["n"] for p in roster_players}
    seen = {sleeper.norm(n) for n in rostered}
    unrostered = []
    for player in list(pool_players) + [{"n": row["name"], "avg": 0.0, "gp": 0}
                                        for row in feed_rows]:
        key = sleeper.norm(player["n"])
        if key not in seen:
            seen.add(key)
            unrostered.append(player)
    rates, missing = {}, []
    for player in roster_players + unrostered:
        projected = overrides.lookup_rate(player["n"])
        if projected is None:
            projected = sleeper.lookup(player["n"], idx)
        if projected is None:
            if player["n"] in rostered:
                missing.append(player["n"])
            projected = sleeper.unprojected_rate(player["avg"], player["gp"])
        rates[player["n"]] = round(projected, 1)
    return rates, missing


def render(rates, feed_date):
    lines = ["// Generated by .claude/skills/projections/extension_data.py from the "
             "projections snapshot (feed %s). Do not edit; `bun run build:only` "
             "regenerates it." % feed_date,
             "export const PLAYER_DATA = {"]
    for name, rate in sorted(rates.items(), key=lambda item: -item[1]):
        lines.append("  %s: { projectedSeasonAvg: %.1f }," % (json.dumps(name, ensure_ascii=False), rate))
    lines += ["};", "",
              "export const NO_PROJECTION_RATE = %.1f;" % sleeper.NO_PROJECTION_RATE, "",
              "export type PlayerData = (typeof PLAYER_DATA)[keyof typeof PLAYER_DATA];", ""]
    return "\n".join(lines)


def write():
    with open(sleeper.SNAPSHOT) as f:
        snap = json.load(f)
    roster_players = []
    for path in sorted(glob.glob(ROSTERS)):
        with open(path) as f:
            roster_players += json.load(f)
    rates, missing = player_rates(roster_players, snap["rows"], last_season_pool())
    with open(OUT, "w") as f:
        f.write(render(rates, sleeper.stamp(snap["updated"])))
    print("wrote %d players -> %s" % (len(rates), os.path.relpath(OUT)))
    if missing:
        print("no projection (last season shrunk toward %.1f): %s"
              % (sleeper.NO_PROJECTION_RATE, ", ".join(sorted(set(missing)))))



def input_paths():
    """Every file `write` reads, plus the code that turns them into rates."""
    code = [__file__, sleeper.__file__, overrides.__file__, sleeper.scoring.__file__]
    return ([sleeper.SNAPSHOT, overrides.OVERRIDES, max(glob.glob(POOL))]
            + sorted(glob.glob(ROSTERS)) + code)


def last_season_pool():
    """Every player in the newest pool as {n, avg, gp} for its latest season
    (`players-2025-26.json` -> "2025"); 0/0 if he didn't play it."""
    path = max(glob.glob(POOL))
    season = os.path.basename(path)[len("players-"):][:4]
    with open(path) as f:
        pool = json.load(f)
    rows = []
    for name, player in pool.items():
        avg, gp = player["seasons"].get(season, (0.0, 0))
        rows.append({"n": name, "avg": avg, "gp": gp})
    return rows


if __name__ == "__main__":
    write()
