"""Offline guard for the extension's player-data file. No network -- fixtures only."""
import json
import os
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import extension_data
import overrides
import sleeper

ROWS = json.load(open(os.path.join(HERE, "fixtures", "sleeper-rows.json")))


def rostered(name, avg=20.0, gp=60):
    return {"n": name, "avg": avg, "gp": gp}


class PlayerRates(unittest.TestCase):
    def test_a_rostered_player_is_keyed_by_the_league_spelling(self):
        rates, _ = extension_data.player_rates([rostered("Michael Porter Jr.")], ROWS)
        expected = sleeper.lookup("Michael Porter", sleeper.index(ROWS))
        self.assertEqual(rates["Michael Porter Jr."], round(expected, 1))
        self.assertNotIn("Michael Porter", rates)

    def test_an_unrostered_feed_player_is_covered_for_a_waiver_pickup(self):
        rates, _ = extension_data.player_rates([rostered("Michael Porter Jr.")], ROWS)
        expected = sleeper.lookup("Giannis Antetokounmpo", sleeper.index(ROWS))
        self.assertEqual(rates["Giannis Antetokounmpo"], round(expected, 1))
        self.assertEqual(len(rates), len(ROWS))

    def test_a_player_with_no_projection_and_no_games_prices_as_a_fringe_body(self):
        rates, missing = extension_data.player_rates([rostered("Emanuel Sharp", avg=0.0, gp=0)], ROWS)
        self.assertEqual(rates["Emanuel Sharp"], sleeper.NO_PROJECTION_RATE)
        self.assertGreater(rates["Emanuel Sharp"], 0)
        self.assertEqual(missing, ["Emanuel Sharp"])

    def test_an_unprojected_rate_trusts_last_season_in_proportion_to_games(self):
        rates, _ = extension_data.player_rates([rostered("Short Sample", avg=17.3, gp=5),
                                                rostered("Full Season", avg=17.3, gp=70)], ROWS)
        self.assertLess(rates["Short Sample"], 12)
        self.assertGreater(rates["Short Sample"], sleeper.NO_PROJECTION_RATE)
        self.assertGreater(rates["Full Season"], 15)
        self.assertLess(rates["Full Season"], 17.3)

    def test_a_rate_override_beats_the_feed(self):
        fd, path = tempfile.mkstemp(suffix=".json")
        os.close(fd)
        real = overrides.OVERRIDES
        try:
            with open(path, "w") as f:
                json.dump({"players": {"Zach Edey": {"rate": 12.0, "reason": "test"}}}, f)
            overrides.OVERRIDES = path
            overrides.index.cache_clear()
            rates, _ = extension_data.player_rates([rostered("Zach Edey")], ROWS)
        finally:
            os.unlink(path)
            overrides.OVERRIDES = real
            overrides.index.cache_clear()
        self.assertEqual(rates["Zach Edey"], 12.0)


class Render(unittest.TestCase):
    def test_renders_the_typescript_module_the_extension_imports(self):
        ts = extension_data.render({"De'Aaron Fox": 33.1, "Nikola Jokić": 60.2},
                                   "2026-09-29")
        self.assertEqual(ts, '''\
// Generated by .claude/skills/projections/extension_data.py from the projections snapshot (feed 2026-09-29). Do not edit; `bun run build:only` regenerates it.
export const PLAYER_DATA = {
  "Nikola Jokić": { projectedSeasonAvg: 60.2 },
  "De'Aaron Fox": { projectedSeasonAvg: 33.1 },
};

export type PlayerData = (typeof PLAYER_DATA)[keyof typeof PLAYER_DATA];
''')


if __name__ == "__main__":
    unittest.main()
